package ccappclient.view.company;

import ccappclient.Client;
import static ccappclient.Client.stringmap;
import static ccappclient.Client.receiveResultSet;
import static ccappclient.Client.sendMessage;
import static ccappclient.Client.sendObject;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import javax.swing.table.TableRowSorter;

public class InsertCompanyTable extends javax.swing.JFrame {

    private EditCompanyDialog dlg;

    /**
     * Creates new form InsertTable
     */
    public InsertCompanyTable() throws IOException {
        dlg = new EditCompanyDialog(this, true);

        initComponents();

        TableRowSorter<CompanyTableModel> sorter = new TableRowSorter<>();
        sorter.setModel((CompanyTableModel) CompanyTable.getModel());
        CompanyTable.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CompanyNameLabel = new javax.swing.JLabel();
        CompanyLocationLabel = new javax.swing.JLabel();
        CompanyNameField = new javax.swing.JTextField();
        CompanyLocationField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ArrayList<String[]> rs = getResultFromCompany();
        CompanyTable = new javax.swing.JTable();
        AddButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        CommentLabel = new javax.swing.JLabel();
        ManufCostsLabel = new javax.swing.JLabel();
        PercentLabel3 = new javax.swing.JLabel();
        GenrunCostsField = new javax.swing.JTextField();
        GenrunCostsLabel = new javax.swing.JLabel();
        PercentLabel4 = new javax.swing.JLabel();
        InsurCostsField = new javax.swing.JTextField();
        InsurCostsLabel = new javax.swing.JLabel();
        PercentLabel5 = new javax.swing.JLabel();
        VATField = new javax.swing.JTextField();
        PercentLabel1 = new javax.swing.JLabel();
        VATLabel = new javax.swing.JLabel();
        SocialChargesField = new javax.swing.JTextField();
        SocialChargesLabel = new javax.swing.JLabel();
        PercentLabel2 = new javax.swing.JLabel();
        ManufCostsField = new javax.swing.JTextField();
        FormTitleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        CompanyNameLabel.setText("Название");

        CompanyLocationLabel.setText("Адрес");

        CompanyLocationField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompanyLocationFieldActionPerformed(evt);
            }
        });

        CompanyTable.setModel(new ccappclient.view.company.CompanyTableModel(rs));
        CompanyTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        CompanyTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CompanyTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CompanyTable);

        AddButton.setText("Зарегистрировать заново");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        EditButton.setText("Редактировать запись");
        EditButton.setEnabled(false);
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Удалить запись");
        DeleteButton.setEnabled(false);
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        BackButton.setText("Назад");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        CommentLabel.setText("  ");

        ManufCostsLabel.setText("Общепроизводств. расходы:");

        PercentLabel3.setText("%");

        GenrunCostsLabel.setText("Общехозяйств. расходы:");

        PercentLabel4.setText("%");

        InsurCostsLabel.setText("Обяз. страх. от несч. случаев:");

        PercentLabel5.setText("%");

        VATField.setToolTipText("");

        PercentLabel1.setText("%");

        VATLabel.setText("НДС:");

        SocialChargesField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SocialChargesFieldActionPerformed(evt);
            }
        });

        SocialChargesLabel.setText("Отчисления на соц. нужды:");

        PercentLabel2.setText("%");

        FormTitleLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        FormTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FormTitleLabel.setText("Данные о предприятии");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CommentLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FormTitleLabel)
                .addGap(114, 114, 114))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EditButton)
                                .addGap(42, 42, 42)
                                .addComponent(DeleteButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CompanyLocationLabel)
                                    .addComponent(CompanyNameLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(VATLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(SocialChargesLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ManufCostsLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(GenrunCostsLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(InsurCostsLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                .addComponent(VATField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(SocialChargesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ManufCostsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(InsurCostsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(GenrunCostsField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(PercentLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(PercentLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(PercentLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(PercentLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(PercentLabel5)))
                                    .addComponent(CompanyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(CompanyLocationField)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {GenrunCostsField, InsurCostsField, ManufCostsField, SocialChargesField, VATField});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {CompanyLocationField, CompanyNameField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FormTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CompanyNameLabel)
                    .addComponent(CompanyNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CompanyLocationLabel)
                    .addComponent(CompanyLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VATField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VATLabel)
                    .addComponent(PercentLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SocialChargesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SocialChargesLabel)
                    .addComponent(PercentLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManufCostsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ManufCostsLabel)
                    .addComponent(PercentLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GenrunCostsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenrunCostsLabel)
                    .addComponent(PercentLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsurCostsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InsurCostsLabel)
                    .addComponent(PercentLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(AddButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CommentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DeleteButton)
                    .addComponent(EditButton))
                .addGap(13, 13, 13)
                .addComponent(BackButton)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
//        try {
//            mdbc.close(stmt.getResultSet());
//            mdbc.destroy();
//        } catch (SQLException ex) {
//            System.out.println("formWindowClosing = " + ex);
//        }
    }//GEN-LAST:event_formWindowClosing

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        sendMessage("_send_button");
        //String CompanyID = CompanyIDField.getText();
        String CompanyName = CompanyNameField.getText();
        String CompanyLocation = CompanyLocationField.getText();
        String VAT = VATField.getText();
        String SocialCharges = SocialChargesField.getText();
        String ManufCosts = ManufCostsField.getText();
        String GenrunCosts = GenrunCostsField.getText();
        String InsurCosts = InsurCostsField.getText();
        stringmap = new LinkedHashMap<>();
        //stringmap.put("CompanyID", CompanyID);
        stringmap.put("CompanyName", CompanyName);
        stringmap.put("CompanyLocation", CompanyLocation);
        stringmap.put("VAT", VAT);
        stringmap.put("SocialCharges", SocialCharges);
        stringmap.put("ManufCosts", ManufCosts);
        stringmap.put("GenrunCosts", GenrunCosts);
        stringmap.put("InsurCosts", InsurCosts);
        sendObject(stringmap);
        //CommentLabel.setText(Client.receiveMessage());
        //CommentLabel.setText("1 row inserted");
        //updateComponents();
    }//GEN-LAST:event_AddButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        sendMessage("_delete_button");
        String CompanyID = (String) CompanyTable.getValueAt(CompanyTable.getSelectedRow(), 0);
        stringmap = new LinkedHashMap<>();
        stringmap.put("CompanyID", CompanyID);

        sendObject(stringmap);

        //CommentLabel.setText((String) Client.receiveMessage());
        //CommentLabel.setText("1 row deleted");
        //updateComponents();
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:

        sendMessage("_edit_button");

        //dlg.setCompanyID((String) CompanyTable.getValueAt(CompanyTable.getSelectedRow(), 0));
        dlg.setCompanyName((String) CompanyTable.getValueAt(CompanyTable.getSelectedRow(), 1));
        dlg.setCompanyLocation((String) CompanyTable.getValueAt(CompanyTable.getSelectedRow(), 2));
        dlg.setVAT((String) CompanyTable.getValueAt(CompanyTable.getSelectedRow(), 3));
        dlg.setSocialCharges((String) CompanyTable.getValueAt(CompanyTable.getSelectedRow(), 4));
        dlg.setManufCosts((String) CompanyTable.getValueAt(CompanyTable.getSelectedRow(), 5));
        dlg.setGenrunCosts((String) CompanyTable.getValueAt(CompanyTable.getSelectedRow(), 6));
        dlg.setInsurCosts((String) CompanyTable.getValueAt(CompanyTable.getSelectedRow(), 7));
        dlg.setVisible(true);

        stringmap = new LinkedHashMap<>();

        //stringmap.put("CompanyID", dlg.getCompanyID());
        stringmap.put("CompanyID", (String) CompanyTable.getValueAt(CompanyTable.getSelectedRow(), 0));
        stringmap.put("CompanyName", dlg.getCompanyName());
        stringmap.put("CompanyLocation", dlg.getCompanyLocation());
        stringmap.put("VAT", dlg.getVAT());
        stringmap.put("SocialCharges", dlg.getSocialCharges());
        stringmap.put("ManufCosts", dlg.getManufCosts());
        stringmap.put("GenrunCosts", dlg.getGenrunCosts());
        stringmap.put("InsurCosts", dlg.getInsurCosts());

        sendObject(stringmap);
        
        //CommentLabel.setText((String) Client.receiveMessage());
        //updateComponents();
    }//GEN-LAST:event_EditButtonActionPerformed

    private void CompanyTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CompanyTableMouseClicked
        // TODO add your handling code here:
        if (CompanyTable.getSelectedRowCount() > 0) {
            EditButton.setEnabled(true);
            DeleteButton.setEnabled(true);
        } else {
            EditButton.setEnabled(false);
            DeleteButton.setEnabled(false);
        }
    }//GEN-LAST:event_CompanyTableMouseClicked

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:

        sendMessage("_go_back");
        //this.setVisible(false);
        //new MenuAdmin().setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void SocialChargesFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SocialChargesFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SocialChargesFieldActionPerformed

    private void CompanyLocationFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompanyLocationFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompanyLocationFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InsertCompanyTable().setVisible(true);
                } catch (IOException e) {
                    System.out.println("InsertCompanyTable run = " + e);
                }
            }
        });
    }

    public void updateComponents() {
        getContentPane().removeAll();
        initComponents();
    }

    public ArrayList<String[]> getResultFromCompany() {
        ArrayList<String[]> rs = null;

        sendMessage("_get_result_from_company");
        rs = receiveResultSet();
        return rs;
    }

    public String quotate(String content) {
        return " '" + content + "' ";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel CommentLabel;
    private javax.swing.JTextField CompanyLocationField;
    private javax.swing.JLabel CompanyLocationLabel;
    private javax.swing.JTextField CompanyNameField;
    private javax.swing.JLabel CompanyNameLabel;
    private javax.swing.JTable CompanyTable;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JLabel FormTitleLabel;
    private javax.swing.JTextField GenrunCostsField;
    private javax.swing.JLabel GenrunCostsLabel;
    private javax.swing.JTextField InsurCostsField;
    private javax.swing.JLabel InsurCostsLabel;
    private javax.swing.JTextField ManufCostsField;
    private javax.swing.JLabel ManufCostsLabel;
    private javax.swing.JLabel PercentLabel1;
    private javax.swing.JLabel PercentLabel2;
    private javax.swing.JLabel PercentLabel3;
    private javax.swing.JLabel PercentLabel4;
    private javax.swing.JLabel PercentLabel5;
    private javax.swing.JTextField SocialChargesField;
    private javax.swing.JLabel SocialChargesLabel;
    private javax.swing.JTextField VATField;
    private javax.swing.JLabel VATLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
