/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ccappclient.view.calculating;

import static ccappclient.Client.stringmap;
import static ccappclient.Client.receiveResultSet;
import static ccappclient.Client.sendMessage;
import static ccappclient.Client.sendObject;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author M4RT1H
 */
public class InsertCalculatingTable extends javax.swing.JFrame {

    private EditCalculatingDialog dlg;

    /**
     * Creates new form InsertTable
     */
    public InsertCalculatingTable() throws IOException {
        dlg = new EditCalculatingDialog(this, true);

        initComponents();
        initCompanyParameters();

        TableRowSorter<CalculatingTableModel> sorter = new TableRowSorter<>();
        sorter.setModel((CalculatingTableModel) CalculatingTable.getModel());
        CalculatingTable.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProductIDLabel = new javax.swing.JLabel();
        CalculatingDateLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ArrayList<String[]> rs = getResultFromCalculating();
        CalculatingTable = new javax.swing.JTable();
        SendButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        EnergyCostsLabel = new javax.swing.JLabel();
        EnergyCostsFiled = new javax.swing.JTextField();
        SalaryFiled = new javax.swing.JTextField();
        SalaryLabel = new javax.swing.JLabel();
        RubLabel1 = new javax.swing.JLabel();
        RubLabel2 = new javax.swing.JLabel();
        PercentLabel2 = new javax.swing.JLabel();
        SocialChargesField = new javax.swing.JTextField();
        SocialChargesLabel = new javax.swing.JLabel();
        GenrunCostsField = new javax.swing.JTextField();
        GenrunCostsLabel = new javax.swing.JLabel();
        PercentLabel3 = new javax.swing.JLabel();
        PercentLabel4 = new javax.swing.JLabel();
        ManufCostsField = new javax.swing.JTextField();
        ManufCostsLabel = new javax.swing.JLabel();
        InsurCostsLabel = new javax.swing.JLabel();
        InsurCostsField = new javax.swing.JTextField();
        PercentLabel5 = new javax.swing.JLabel();
        MonthsCombo = new javax.swing.JComboBox();
        ProductIDCombo = new javax.swing.JComboBox();
        ChartButton = new javax.swing.JButton();
        parametersCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        ProductIDLabel.setText("ID Продукта");

        CalculatingDateLabel.setText("Месяц расчёта");

        CalculatingTable.setModel(new ccappclient.view.calculating.CalculatingTableModel(rs));
        CalculatingTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        CalculatingTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalculatingTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(CalculatingTable);

        SendButton.setText("Рассчитать");
        SendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButtonActionPerformed(evt);
            }
        });

        EditButton.setText("Изменить месяц");
        EditButton.setEnabled(false);
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Удалить запись");
        DeleteButton.setEnabled(false);
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        BackButton.setText("Назад");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        EnergyCostsLabel.setText("Расходы на электроэнергию:");

        EnergyCostsFiled.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        SalaryFiled.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        SalaryLabel.setText("Зарплата произв. рабочих:");

        RubLabel1.setText("руб.");

        RubLabel2.setText("руб.");

        PercentLabel2.setText("%");

        SocialChargesField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SocialChargesField.setEnabled(false);

        SocialChargesLabel.setText("Отчисления на соц. нужды: ");

        GenrunCostsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        GenrunCostsField.setEnabled(false);

        GenrunCostsLabel.setText("Общехозяйственные расходы: ");

        PercentLabel3.setText("%");

        PercentLabel4.setText("%");

        ManufCostsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ManufCostsField.setEnabled(false);
        ManufCostsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManufCostsFieldActionPerformed(evt);
            }
        });

        ManufCostsLabel.setText("Общепроизводственные расходы: ");

        InsurCostsLabel.setText("Обязат страх от несч.случаев:");

        InsurCostsField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        InsurCostsField.setEnabled(false);

        PercentLabel5.setText("%");

        MonthsCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь" }));

        ProductIDCombo.setModel(new javax.swing.DefaultComboBoxModel(getIDsFromProducts()));

        ChartButton.setText("График стоимости");
        ChartButton.setEnabled(false);
        ChartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChartButtonActionPerformed(evt);
            }
        });

        parametersCheckBox.setText("<html>Указать<br>другие</html>");
        parametersCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parametersCheckBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("2021");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(EditButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(ChartButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DeleteButton)))
                                .addGap(0, 28, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(EnergyCostsLabel)
                                    .addComponent(SalaryLabel)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CalculatingDateLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ProductIDLabel, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(SalaryFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(RubLabel2))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(EnergyCostsFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(RubLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(MonthsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ProductIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(GenrunCostsField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(InsurCostsField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PercentLabel5)
                                    .addComponent(PercentLabel3))
                                .addGap(24, 24, 24)
                                .addComponent(parametersCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ManufCostsLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(GenrunCostsLabel)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SocialChargesLabel)
                                    .addComponent(InsurCostsLabel))))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ManufCostsField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PercentLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(SocialChargesField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PercentLabel2)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductIDLabel)
                    .addComponent(ProductIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CalculatingDateLabel)
                    .addComponent(MonthsCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalaryLabel)
                    .addComponent(SalaryFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RubLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EnergyCostsLabel)
                    .addComponent(EnergyCostsFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RubLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SocialChargesLabel)
                    .addComponent(SocialChargesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PercentLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(InsurCostsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InsurCostsLabel)
                            .addComponent(PercentLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GenrunCostsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GenrunCostsLabel)
                            .addComponent(PercentLabel3))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(parametersCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManufCostsLabel)
                    .addComponent(ManufCostsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PercentLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(SendButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditButton)
                    .addComponent(ChartButton)
                    .addComponent(DeleteButton))
                .addGap(13, 13, 13)
                .addComponent(BackButton)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
//        try {
//            mdbc.close(stmt.getResultSet());
//            mdbc.destroy();
//        } catch (SQLException ex) {
//            System.out.println("formWindowClosing = " + ex);
//        }
    }//GEN-LAST:event_formWindowClosing

    private void SendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButtonActionPerformed
        sendMessage("_send_button");
        //String CalculatingID = CalculatingIDField.getText();
        String ProductID = (String) ProductIDCombo.getSelectedItem();
        //String ProductCost = ProductCostField.getText();
        String CalculatingDate = (String) MonthsCombo.getSelectedItem();
        String EnergyCosts = EnergyCostsFiled.getText();
        String Salary = SalaryFiled.getText();

        stringmap = new LinkedHashMap<>();
        //stringmap.put("CalculatingID", CalculatingID);
        stringmap.put("ProductID", ProductID);
        //stringmap.put("ProductCost", ProductCost);
        stringmap.put("CalculatingDate", CalculatingDate);
        stringmap.put("EnergyCosts", EnergyCosts);
        stringmap.put("Salary", Salary);
        sendObject(stringmap);
        //CommentLabel.setText(Client.receiveMessage());
        //CommentLabel.setText("1 row inserted");
        //updateComponents();
    }//GEN-LAST:event_SendButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        sendMessage("_delete_button");
        String CalculatingID = (String) CalculatingTable.getValueAt(CalculatingTable.getSelectedRow(), 0);
        stringmap = new LinkedHashMap<>();
        stringmap.put("CalculatingID", CalculatingID);

        sendObject(stringmap);

        //CommentLabel.setText((String) Client.receiveMessage());
        //CommentLabel.setText("1 row deleted");
        //updateComponents();
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:

        sendMessage("_edit_button");

        //dlg.setCalculatingID((String) CalculatingTable.getValueAt(CalculatingTable.getSelectedRow(), 0));
        //dlg.setProductID((String) CalculatingTable.getValueAt(CalculatingTable.getSelectedRow(), 1));
        //dlg.setProductCost((String) CalculatingTable.getValueAt(CalculatingTable.getSelectedRow(), 2));
        dlg.setSelectedMonthsCombo((String) CalculatingTable.getValueAt(CalculatingTable.getSelectedRow(), 3));
        dlg.setVisible(true);

        stringmap = new LinkedHashMap<>();

        //stringmap.put("CalculatingID", dlg.getCalculatingID());
        stringmap.put("CalculatingID", (String) CalculatingTable.getValueAt(CalculatingTable.getSelectedRow(), 0));
        //stringmap.put("ProductID", dlg.getProductID());
        //stringmap.put("ProductCost", dlg.getProductCost());
        stringmap.put("CalculatingDate", dlg.getSelectedMonthsCombo());

        sendObject(stringmap);

        //CommentLabel.setText((String) Client.receiveMessage());
        //updateComponents();
    }//GEN-LAST:event_EditButtonActionPerformed

    private void CalculatingTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalculatingTableMouseClicked
        // TODO add your handling code here:
        if (CalculatingTable.getSelectedRowCount() > 0) {
            EditButton.setEnabled(true);
            DeleteButton.setEnabled(true);
            ChartButton.setEnabled(true);
        } else {
            EditButton.setEnabled(false);
            DeleteButton.setEnabled(false);
            ChartButton.setEnabled(false);
        }
    }//GEN-LAST:event_CalculatingTableMouseClicked

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:

        sendMessage("_go_back");
        //this.setVisible(false);
        //new MenuAdmin().setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ChartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChartButtonActionPerformed
        // TODO add your handling code here:
        sendMessage("_price_chart");
        String productID = (String) CalculatingTable.getValueAt(CalculatingTable.getSelectedRow(), 1);
        sendMessage(productID);
    }//GEN-LAST:event_ChartButtonActionPerformed

    private void parametersCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parametersCheckBoxActionPerformed
        // TODO add your handling code here:
        if (parametersCheckBox.isSelected()) {
            SocialChargesField.setEnabled(true);
            InsurCostsField.setEnabled(true);
            GenrunCostsField.setEnabled(true);
            ManufCostsField.setEnabled(true);
        } else {
            SocialChargesField.setEnabled(false);
            InsurCostsField.setEnabled(false);
            GenrunCostsField.setEnabled(false);
            ManufCostsField.setEnabled(false);
            //initCompanyParameters();
        }
    }//GEN-LAST:event_parametersCheckBoxActionPerformed

    private void ManufCostsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManufCostsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ManufCostsFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InsertCalculatingTable().setVisible(true);
                } catch (IOException e) {
                    System.out.println("InsertCalculatingTable run = " + e);
                }
            }
        });
    }

    public void updateComponents() {
        getContentPane().removeAll();
        initComponents();
    }

    public ArrayList<String[]> getResultFromCalculating() {
        ArrayList<String[]> rs = null;

        sendMessage("_get_result_from_calculating");
        rs = receiveResultSet();
        return rs;
    }

    public ArrayList<String[]> getResultFromCompany() {
        ArrayList<String[]> rs = null;

        sendMessage("_get_result_from_company");
        rs = receiveResultSet();
        return rs;
    }

    public void initCompanyParameters() {
        ArrayList<String[]> resultSet = getResultFromCompany();

        //VATField = Double.parseDouble(resultSet.get(resultSet.size() - 1)[3]);
        SocialChargesField.setText(resultSet.get(resultSet.size() - 1)[4]);
        ManufCostsField.setText(resultSet.get(resultSet.size() - 1)[5]);
        GenrunCostsField.setText(resultSet.get(resultSet.size() - 1)[6]);
        InsurCostsField.setText(resultSet.get(resultSet.size() - 1)[7]);

    }

    public String[] getIDsFromProducts() {
        ArrayList<String> arrList = new ArrayList<>();
        ArrayList<String[]> rs = null;

        sendMessage("_get_ids_from_products");
        rs = receiveResultSet();
        for (int i = 0; i < rs.size(); i++) {
            arrList.add(rs.get(i)[0]);
        }
        return arrList.toArray(new String[arrList.size()]);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel CalculatingDateLabel;
    private javax.swing.JTable CalculatingTable;
    private javax.swing.JButton ChartButton;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JTextField EnergyCostsFiled;
    private javax.swing.JLabel EnergyCostsLabel;
    private javax.swing.JTextField GenrunCostsField;
    private javax.swing.JLabel GenrunCostsLabel;
    private javax.swing.JTextField InsurCostsField;
    private javax.swing.JLabel InsurCostsLabel;
    private javax.swing.JTextField ManufCostsField;
    private javax.swing.JLabel ManufCostsLabel;
    private javax.swing.JComboBox MonthsCombo;
    private javax.swing.JLabel PercentLabel2;
    private javax.swing.JLabel PercentLabel3;
    private javax.swing.JLabel PercentLabel4;
    private javax.swing.JLabel PercentLabel5;
    private javax.swing.JComboBox ProductIDCombo;
    private javax.swing.JLabel ProductIDLabel;
    private javax.swing.JLabel RubLabel1;
    private javax.swing.JLabel RubLabel2;
    private javax.swing.JTextField SalaryFiled;
    private javax.swing.JLabel SalaryLabel;
    private javax.swing.JButton SendButton;
    private javax.swing.JTextField SocialChargesField;
    private javax.swing.JLabel SocialChargesLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox parametersCheckBox;
    // End of variables declaration//GEN-END:variables
}
