/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ccappclient.view.products;

import static ccappclient.Client.stringmap;
import static ccappclient.Client.receiveResultSet;
import static ccappclient.Client.sendMessage;
import static ccappclient.Client.sendObject;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedHashMap;

public class InsertProductsTable extends javax.swing.JFrame {

    private EditProductDialog dlg;
    private EditMatRatesDialog dlgMatRates;

    /**
     * Creates new form InsertTable
     */
    public InsertProductsTable() throws IOException {
        dlg = new EditProductDialog(this, true);
        dlgMatRates = new EditMatRatesDialog(this, true, getIDsFromMaterials());

        initComponents();

//        TableRowSorter<ProductsTableModel> sortProd = new TableRowSorter<>();
//        sortProd.setModel((ProductsTableModel) MaterialsRatesTable.getModel());
//        MaterialsRatesTable.setRowSorter(sortProd);
//        
//        TableRowSorter<MaterialsRatesTableModel> sortMatRat = new TableRowSorter<>();
//        sortMatRat.setModel((MaterialsRatesTableModel) ProductsTable.getModel());
//        MaterialsRatesTable.setRowSorter(sortMatRat);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ProductIDLabel = new javax.swing.JLabel();
        ProductNameLabel = new javax.swing.JLabel();
        ProductIDField = new javax.swing.JTextField();
        ProductNameField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ArrayList<String[]> rs = getResultFromProducts();
        ProductsTable = new javax.swing.JTable();
        SendButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        CommentLabel = new javax.swing.JLabel();
        MaterialIDCombo = new javax.swing.JComboBox();
        MaterialIDLabel = new javax.swing.JLabel();
        MaterialRateField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        MaterialMeasureLabel = new javax.swing.JLabel();
        SendButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ArrayList<String[]> rsmr = getResultFromMaterialsRates();
        MaterialsRatesTable = new javax.swing.JTable();
        EditButton1 = new javax.swing.JButton();
        DeleteButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        ProductIDLabel.setText("ID Изделия");
        ProductIDLabel.setEnabled(false);

        ProductNameLabel.setText("Название Изделия");

        ProductIDField.setEnabled(false);

        ProductsTable.setModel(new ccappclient.view.products.ProductsTableModel(rs));
        ProductsTable.setToolTipText("");
        ProductsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ProductsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ProductsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ProductsTable);

        SendButton.setText("Отправить");
        SendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButtonActionPerformed(evt);
            }
        });

        EditButton.setText("Редактировать запись");
        EditButton.setEnabled(false);
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Удалить запись");
        DeleteButton.setEnabled(false);
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        BackButton.setText("Назад");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        CommentLabel.setText("  ");

        MaterialIDCombo.setModel(new javax.swing.DefaultComboBoxModel(getIDsFromMaterials()));

        MaterialIDLabel.setText("Материал:");

        jLabel1.setText("Норма: ");

        MaterialMeasureLabel.setText("ед.");

        SendButton1.setText("Добавить материал");
        SendButton1.setEnabled(false);
        SendButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButton1ActionPerformed(evt);
            }
        });

        MaterialsRatesTable.setModel(new ccappclient.view.products.MaterialsRatesTableModel(rsmr));
        MaterialsRatesTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        MaterialsRatesTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaterialsRatesTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(MaterialsRatesTable);

        EditButton1.setText("Редактировать запись");
        EditButton1.setEnabled(false);
        EditButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButton1ActionPerformed(evt);
            }
        });

        DeleteButton1.setText("Удалить запись");
        DeleteButton1.setEnabled(false);
        DeleteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(EditButton1)
                        .addGap(79, 79, 79)
                        .addComponent(DeleteButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SendButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(EditButton)
                                        .addGap(79, 79, 79)
                                        .addComponent(DeleteButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(MaterialIDLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MaterialIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MaterialRateField, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(MaterialMeasureLabel))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(3, 3, 3))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductIDLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ProductNameLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductIDField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductNameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(CommentLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ProductIDField, ProductNameField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductIDLabel)
                    .addComponent(ProductIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProductNameLabel)
                    .addComponent(ProductNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(SendButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CommentLabel)
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditButton)
                    .addComponent(DeleteButton))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaterialIDLabel)
                    .addComponent(MaterialIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(MaterialRateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaterialMeasureLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SendButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EditButton1)
                    .addComponent(DeleteButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(BackButton)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
//        try {
//            mdbc.close(stmt.getResultSet());
//            mdbc.destroy();
//        } catch (SQLException ex) {
//            System.out.println("formWindowClosing = " + ex);
//        }
    }//GEN-LAST:event_formWindowClosing

    private void SendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButtonActionPerformed
        sendMessage("_send_button");
        String ProductID = ProductIDField.getText();
        String ProductName = ProductNameField.getText();
        stringmap = new LinkedHashMap<>();
        stringmap.put("ProductID", ProductID);
        stringmap.put("ProductName", ProductName);
        sendObject(stringmap);
        //CommentLabel.setText(Client.receiveMessage());
        //CommentLabel.setText("1 row inserted");
        //updateComponents();
    }//GEN-LAST:event_SendButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        sendMessage("_delete_button");
        String ProductID = (String) ProductsTable.getValueAt(ProductsTable.getSelectedRow(), 0);
        stringmap = new LinkedHashMap<>();
        stringmap.put("ProductID", ProductID);

        sendObject(stringmap);

        //CommentLabel.setText((String) Client.receiveMessage());
        //CommentLabel.setText("1 row deleted");
        //updateComponents();
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:

        sendMessage("_edit_button");

        //dlg.setProductID((String) ProductTable.getValueAt(ProductTable.getSelectedRow(), 0));
        dlg.setProductName((String) ProductsTable.getValueAt(ProductsTable.getSelectedRow(), 1));
        dlg.setVisible(true);

        stringmap = new LinkedHashMap<>();

        //stringmap.put("ProductID", dlg.getProductID());
        stringmap.put("ProductID", (String) ProductsTable.getValueAt(ProductsTable.getSelectedRow(), 0));
        stringmap.put("ProductName", dlg.getProductName());

        sendObject(stringmap);

        //CommentLabel.setText((String) Client.receiveMessage());
        //updateComponents();
    }//GEN-LAST:event_EditButtonActionPerformed

    private void ProductsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ProductsTableMouseClicked
        // TODO add your handling code here:
        if (ProductsTable.getSelectedRowCount() > 0) {
            EditButton.setEnabled(true);
            DeleteButton.setEnabled(true);
            SendButton1.setEnabled(true);
        } else {
            EditButton.setEnabled(false);
            DeleteButton.setEnabled(false);
            SendButton1.setEnabled(false);
        }
    }//GEN-LAST:event_ProductsTableMouseClicked

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:

        sendMessage("_go_back");
    }//GEN-LAST:event_BackButtonActionPerformed

    private void SendButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButton1ActionPerformed
        // TODO add your handling code here:
        sendMessage("_send_button_matrates");
        String ProductID = (String) ProductsTable.getValueAt(ProductsTable.getSelectedRow(), 0);
        String MaterialID = (String) MaterialIDCombo.getSelectedItem();
        String MaterialRate = MaterialRateField.getText();
        stringmap = new LinkedHashMap<>();
        stringmap.put("ProductID", ProductID);
        stringmap.put("MaterialID", MaterialID);
        stringmap.put("MaterialRate", MaterialRate);
        sendObject(stringmap);
    }//GEN-LAST:event_SendButton1ActionPerformed

    private void MaterialsRatesTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaterialsRatesTableMouseClicked
        // TODO add your handling code here:
        if (MaterialsRatesTable.getSelectedRowCount() > 0) {
            EditButton1.setEnabled(true);
            DeleteButton1.setEnabled(true);
        } else {
            EditButton1.setEnabled(false);
            DeleteButton1.setEnabled(false);
        }
    }//GEN-LAST:event_MaterialsRatesTableMouseClicked

    private void EditButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButton1ActionPerformed
        // TODO add your handling code here:
        sendMessage("_edit_button_matrates");

        dlgMatRates.setMaterialID((String) MaterialsRatesTable.getValueAt(MaterialsRatesTable.getSelectedRow(), 2));
        dlgMatRates.setMaterialRate((String) MaterialsRatesTable.getValueAt(MaterialsRatesTable.getSelectedRow(), 3));
        dlgMatRates.setVisible(true);

        stringmap = new LinkedHashMap<>();

        stringmap.put("MaterialRateID", (String) MaterialsRatesTable.getValueAt(MaterialsRatesTable.getSelectedRow(), 0));
        stringmap.put("MaterialID", dlgMatRates.getMaterialID());
        stringmap.put("MaterialRate", dlgMatRates.getMaterialRate());

        sendObject(stringmap);

        //CommentLabel.setText((String) Client.receiveMessage());
        //updateComponents();
    }//GEN-LAST:event_EditButton1ActionPerformed

    private void DeleteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButton1ActionPerformed
        // TODO add your handling code here:
        sendMessage("_delete_button_matrates");
        String MaterialRateID = (String) MaterialsRatesTable.getValueAt(MaterialsRatesTable.getSelectedRow(), 0);
        stringmap = new LinkedHashMap<>();
        stringmap.put("MaterialRateID", MaterialRateID);

        sendObject(stringmap);
    }//GEN-LAST:event_DeleteButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InsertProductsTable().setVisible(true);
                } catch (IOException e) {
                    System.out.println("InsertProductsTable run = " + e);
                }
            }
        });
    }

    public void updateComponents() {
        getContentPane().removeAll();
        initComponents();
    }

    public ArrayList<String[]> getResultFromMaterialsRates() {
        ArrayList<String[]> rs = null;

        sendMessage("_get_result_from_materials_rates");
        rs = receiveResultSet();
        return rs;
    }

    public ArrayList<String[]> getResultFromProducts() {
        ArrayList<String[]> rs = null;

        sendMessage("_get_result_from_products");
        rs = receiveResultSet();
        return rs;
    }

    public String[] getIDsFromMaterials() {
        ArrayList<String> arrList = new ArrayList<>();
        ArrayList<String[]> rs = null;

        sendMessage("_get_ids_from_materials");
        rs = receiveResultSet();
        for (int i = 0; i < rs.size(); i++) {
            arrList.add(rs.get(i)[0]);
        }
        return arrList.toArray(new String[arrList.size()]);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel CommentLabel;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton DeleteButton1;
    private javax.swing.JButton EditButton;
    private javax.swing.JButton EditButton1;
    private javax.swing.JComboBox MaterialIDCombo;
    private javax.swing.JLabel MaterialIDLabel;
    private javax.swing.JLabel MaterialMeasureLabel;
    private javax.swing.JTextField MaterialRateField;
    private javax.swing.JTable MaterialsRatesTable;
    private javax.swing.JTextField ProductIDField;
    private javax.swing.JLabel ProductIDLabel;
    private javax.swing.JTextField ProductNameField;
    private javax.swing.JLabel ProductNameLabel;
    private javax.swing.JTable ProductsTable;
    private javax.swing.JButton SendButton;
    private javax.swing.JButton SendButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
