package ccappclient.view.materials;

import ccappclient.Client;
import static ccappclient.Client.stringmap;
import static ccappclient.Client.receiveResultSet;
import static ccappclient.Client.sendMessage;
import static ccappclient.Client.sendObject;
import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import javax.swing.table.TableRowSorter;

public class InsertMaterialsTable extends javax.swing.JFrame {

    private EditMaterialDialog dlg;

    /**
     * Creates new form InsertTable
     */
    public InsertMaterialsTable() throws IOException {
        dlg = new EditMaterialDialog(this, true);

        initComponents();

        TableRowSorter<MaterialsTableModel> sorter = new TableRowSorter<>();
        sorter.setModel((MaterialsTableModel) MaterialsTable.getModel());
        MaterialsTable.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MaterialIDLabel = new javax.swing.JLabel();
        MaterialNameLabel = new javax.swing.JLabel();
        MaterialPriceLabel = new javax.swing.JLabel();
        MaterialIDField = new javax.swing.JTextField();
        MaterialNameField = new javax.swing.JTextField();
        MaterialPriceField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ArrayList<String[]> rs = getResultFromMaterials();
        MaterialsTable = new javax.swing.JTable();
        SendButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        CommentLabel = new javax.swing.JLabel();
        MaterialMeasureLabel = new javax.swing.JLabel();
        MaterialMeasureField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        MaterialIDLabel.setText("ID Материала");
        MaterialIDLabel.setEnabled(false);

        MaterialNameLabel.setText("Название Материала");

        MaterialPriceLabel.setText("Цена Материала");

        MaterialIDField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        MaterialIDField.setEnabled(false);

        MaterialNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        MaterialPriceField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        MaterialsTable.setModel(new ccappclient.view.materials.MaterialsTableModel(rs));
        MaterialsTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        MaterialsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaterialsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(MaterialsTable);

        SendButton.setText("Отправить");
        SendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendButtonActionPerformed(evt);
            }
        });

        EditButton.setText("Редактировать запись");
        EditButton.setEnabled(false);
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("Удалить запись");
        DeleteButton.setEnabled(false);
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });

        BackButton.setText("Назад");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        CommentLabel.setText("  ");

        MaterialMeasureLabel.setText("Единицы измерения");

        MaterialMeasureField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(CommentLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SendButton, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(DeleteButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(MaterialIDLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(MaterialNameLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(MaterialIDField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(MaterialNameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(MaterialPriceLabel)
                                            .addComponent(MaterialMeasureLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(MaterialMeasureField)
                                            .addComponent(MaterialPriceField))))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {MaterialIDField, MaterialNameField, MaterialPriceField});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaterialIDLabel)
                    .addComponent(MaterialIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaterialNameLabel)
                    .addComponent(MaterialNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaterialPriceLabel)
                    .addComponent(MaterialPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MaterialMeasureLabel)
                    .addComponent(MaterialMeasureField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(SendButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CommentLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeleteButton)
                    .addComponent(EditButton))
                .addGap(13, 13, 13)
                .addComponent(BackButton)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
//        try {
//            mdbc.close(stmt.getResultSet());
//            mdbc.destroy();
//        } catch (SQLException ex) {
//            System.out.println("formWindowClosing = " + ex);
//        }
    }//GEN-LAST:event_formWindowClosing

    private void SendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendButtonActionPerformed
        sendMessage("_send_button");
        String MaterialID = MaterialIDField.getText();
        String MaterialName = MaterialNameField.getText();
        String MaterialPrice = MaterialPriceField.getText();
        String MaterialMeasure = MaterialMeasureField.getText();
        stringmap = new LinkedHashMap<>();
        stringmap.put("MaterialID", MaterialID);
        stringmap.put("MaterialName", MaterialName);
        stringmap.put("MaterialPrice", MaterialPrice);
        stringmap.put("MaterialMeasure", MaterialMeasure);
        sendObject(stringmap);
        //CommentLabel.setText(Client.receiveMessage());
        //CommentLabel.setText("1 row inserted");
        //updateComponents();
    }//GEN-LAST:event_SendButtonActionPerformed

    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtonActionPerformed
        // TODO add your handling code here:
        sendMessage("_delete_button");
        String MaterialID = (String) MaterialsTable.getValueAt(MaterialsTable.getSelectedRow(), 0);
        stringmap = new LinkedHashMap<>();
        stringmap.put("MaterialID", MaterialID);

        sendObject(stringmap);

        //CommentLabel.setText((String) Client.receiveMessage());
        //CommentLabel.setText("1 row deleted");
        //updateComponents();
    }//GEN-LAST:event_DeleteButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:

        sendMessage("_edit_button");

        //dlg.setMaterialID((String) MaterialTable.getValueAt(MaterialTable.getSelectedRow(), 0));
        dlg.setMaterialName((String) MaterialsTable.getValueAt(MaterialsTable.getSelectedRow(), 1));
        dlg.setMaterialPrice((String) MaterialsTable.getValueAt(MaterialsTable.getSelectedRow(), 2));
        dlg.setMaterialMeasure((String) MaterialsTable.getValueAt(MaterialsTable.getSelectedRow(), 3));
        dlg.setVisible(true);

        stringmap = new LinkedHashMap<>();

        //stringmap.put("MaterialID", dlg.getMaterialID());
        stringmap.put("MaterialID", (String) MaterialsTable.getValueAt(MaterialsTable.getSelectedRow(), 0));
        stringmap.put("MaterialName", dlg.getMaterialName());
        stringmap.put("MaterialPrice", dlg.getMaterialPrice());
        stringmap.put("MaterialMeasure", dlg.getMaterialMeasure());

        sendObject(stringmap);
        
        //CommentLabel.setText((String) Client.receiveMessage());
        //updateComponents();
    }//GEN-LAST:event_EditButtonActionPerformed

    private void MaterialsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaterialsTableMouseClicked
        // TODO add your handling code here:
        if (MaterialsTable.getSelectedRowCount() > 0) {
            EditButton.setEnabled(true);
            DeleteButton.setEnabled(true);
        } else {
            EditButton.setEnabled(false);
            DeleteButton.setEnabled(false);
        }
    }//GEN-LAST:event_MaterialsTableMouseClicked

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:

        sendMessage("_go_back");
        //this.setVisible(false);
        //new MenuAdmin().setVisible(true);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InsertMaterialsTable().setVisible(true);
                } catch (IOException e) {
                    System.out.println("InsertMaterialsTable run = " + e);
                }
            }
        });
    }

    public void updateComponents() {
        getContentPane().removeAll();
        initComponents();
    }

    public ArrayList<String[]> getResultFromMaterials() {
        ArrayList<String[]> rs = null;

        sendMessage("_get_result_from_materials");
        rs = receiveResultSet();
        return rs;
    }

    public String quotate(String content) {
        return " '" + content + "' ";
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel CommentLabel;
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton EditButton;
    private javax.swing.JTextField MaterialIDField;
    private javax.swing.JLabel MaterialIDLabel;
    private javax.swing.JTextField MaterialMeasureField;
    private javax.swing.JLabel MaterialMeasureLabel;
    private javax.swing.JTextField MaterialNameField;
    private javax.swing.JLabel MaterialNameLabel;
    private javax.swing.JTextField MaterialPriceField;
    private javax.swing.JLabel MaterialPriceLabel;
    private javax.swing.JTable MaterialsTable;
    private javax.swing.JButton SendButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
